# Some "taps" for installing CLI apps
# tap "homebrew/core"
# tap "homebrew/bundle"
tap "eth-p/software"
tap "go-task/tap"

# Binaries & CLI tools
brew "go-task"
brew "mdbook"
brew "glow"
brew "neovim"
brew "bat"
brew "bat-extras-batman"
brew "bat-extras-batdiff"
brew "chezmoi"
brew "gcc"
brew "fish"
brew "exa"
brew "gh"

brew "poetry"
brew "pre-commit"

brew "unzip"
brew "docker-compose"
