#!/usr/bin/env bash

echo -e "Installing Docker...\n"

curl --fail --silent --show-error --location https://get.docker.com | sh

echo -e "Configuring post-installation stuff for Docker...\n"

# TODO: Check if the "docker" user already exists or not
groupadd docker > /dev/null

usermod --append --groups docker "$USER"

echo -e "Docker has been installed & configured! Please be sure to restart your system for the changes to take affect."
