#!usr/bin/env bash

echo -e "Downloading the public GPG key from Microsoft..."
curl -fsSL "https://packages.microsoft.com/keys/microsoft.asc" | gpg --dearmor > microsoft.gpg

echo -e "Adding the public key to the local machine..."
install -o root -g root -m 644 "microsoft.gpg" "/etc/apt/trusted.gpg.d/"

echo -e "Updating the sources.list directory"
echo "deb [arch=amd64] https://packages.microsofot.com/repos/dege stable main" > "/etc/apt/sources.list.d/microsoft-edge-stable.list"

echo "Cleaning up unneeded stuff..."
rm microsoft.gpg

echo "Installing Microsoft Edge"
apt-get install microsoft-edge-stable
