#!/usr/bin/env bash

# Create a new directory & enter it
function mkd() {
  mkdir -p "$@" && cd "$_"
}

# TODO: Create a .tar.gz archive using gzip compression
# Refer to: https://github.com/mathiasbynens/dotfiles/blob/66ba9b3cc0ca1b29f04b8e39f84e5b034fdb24b6/.functions#L13

# Determine size of a file or total size of a directory
# TODO: Explain what's going on in the function code
function fs() {
  if du -b /dev/null >/dev/null 2>&1; then
    local arg=-sbh
  else
    local arg=-sb
  fi

  if [[ -n $@ ]]; then
    du $arg -- "$@"
  else
    du $arg .[^.]* ./*
  fi
}

# TODO: Use "git" colored diff when available over the "batdiff"
# Refer to: https://github.com/mathiasbynens/dotfiles/blob/66ba9b3cc0ca1b29f04b8e39f84e5b034fdb24b6/.functions#L61

if [ ! $(uname -s) = 'Linux' ]; then
    if [ $(uname -r) | grep -i 'microsoft' ]; then
    # Linux on Windows using WSL2
    alias open='explorer.exe';
  else
    alias open='xdg-open'
  fi
fi

# TODO: Create function wrapping Hugo, invoking which will "cd" into
# "~/projects/blog" & start a dev server as well

################################################################################
################################################################################
#                                                                              #
# Update the Kitty terminal by invoking a single command on the CLI            #
#                                                                              #
# GLOBALS:                                                                     #
#   None                                                                       #
#                                                                              #
# ARGUMENTS:                                                                   #
#   None                                                                       #
#                                                                              #
# OUTPUTS:                                                                     #
#   None                                                                       #
#                                                                              #
# RETURNS:                                                                     #
#   None                                                                       #
#                                                                              #
################################################################################
################################################################################
function update_kitty() {
  # TODO: Customise the installation procedure as detailed in the docs below:
  # https://sw.kovidgoyal.net/kitty/binary/#customizing-the-installation
  curl -fsSL https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
}
