repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
          - id: detect-private-key

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: shfmt
            args: ["-i 2 -ci -bn"]

    - repo: https://github.com/JohnnyMorganz/StyLua
      rev: v0.17.1
      hooks:
          - id: stylua

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.275
      hooks:
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix]

    # TODO: Add a pre-commit hook for Selene
