name: Name of the GitHub Workflow

on:
  push:
    branches:
      - "main"

jobs:
  job-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Contents of the Repository
        uses: actions/checkout@v3

      - name: Perform the Rest of the Intended Logic
        run: echo "Hello World!"
