#!/usr/bin/env zsh

# A bunch of custom aliases for easier terminal usage.
alias ct="cookiecutter"
alias pcs="pre-commit sample-config >> .pre-commit-config.yaml && pre-commit autoupdate &>/dev/null"

# Docker commands
alias compose="docker compose"
alias dps="docker ps --format 'table {{ .ID }}\t{{ .Names }}\t{{ .Ports }}'"
alias dimc="docker image prune --force"
alias drmi="docker image rm"
alias dcdown="docker compose down --remove-orphans --volumes"
alias dcup="docker compose up --detach"
alias dclogs="docker compose logs"
alias dims="docker images"

# Easy and utilitarian aliases for quick terminal usage
alias reload="source $HOME/.zshrc"
alias top="btop --utf-force"
alias cm="cmatrix -abs"
alias rands="openssl rand -base64 32"
alias ll="eza --long --all --classify --icons --git --ignore-glob='.git'"
alias loc="wc -l"
alias mkvenv="python3 -m venv .venv"
alias tree="eza --tree --all --icons --ignore-glob='.git' --git-ignore"
alias dateiso="date +%Y-%m-%dT%H:%M:%S%z"

# Spin dev/experimental databases
alias pgdb="docker run --detach --name postgresql --rm -p 5432:5432 \
    -e POSTGRESQL_USERNAME=psqladmin \
    -e POSTGRESQL_PASSWORD=admin \
    -e POSTGRESQL_DATABASE=postgres \
    bitnami/postgresql:16"
alias rsdb="docker run --name redis --rm -p 6379:6379 \
    -e ALLOW_EMPTY_PASSWORD=yes \
    bitnami/redis:7.2"

alias py="python3"

# Terraform related aliases
alias tfinit="terraform init"
alias tfval="terraform validate"
alias tfplan="terraform plan"

# NPM aliases
alias npm="pnpm"
alias npx="pnpm dlx"

# Google's webp CLI alias
alias webp="cwebp"

# A bunch of Tmux aliases for easier multiplex usage
alias tls="tmux list-session"
alias tnew="tmux new-session"
alias dots="tmux new-session -s dotfiles -n dotfiles -c ~/.dotfiles"
alias tks="tmux kill-server"
