#!/usr/bin/env zsh

# This script contains a bunch of utility functions to make life on the terminal easier

# Create a directory and then "cd" into
mkc() {
    if [[ -n "$1" ]]; then
        mkdir --parents "$1" && cd "$1"
    else
        echo "usage: mkc <name>"
    fi
}

# Stop and remove a running Docker Container
dcs() {
    if [[ -n "$1" ]]; then
        docker container stop $1
        docker container remove $1 --volumes
    else
        echo "usage: dcs <docker-container-name>"
    fi
}
