" Required & minimal options
set nocompatible
set number relativenumber
set clipboard=unnamedplus
set hidden
set nowrap
set ruler
set encoding=utf-8
set backspace=indent,eol,start
set lazyredraw
set showmatch
set nohlsearch incsearch
set noswapfile
set ignorecase
set termguicolors
set tabstop=4 softtabstop=4 expandtab shiftwidth=4

filetype plugin indent on

if !exists("g:syntax_on")
    syntax enable
endif

" Add plugins
call plug#begin('~/.vimfiles/plugged')
Plug 'itchyny/lightline.vim'
Plug 'arcticicestudio/nord-vim'
call plug#end()

" Set up colour schemes
colorscheme nord
let g:lightline = { 'colorscheme' : 'nord' }

set noshowmode
set laststatus=2

" Disale arrow keys
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>
