--[[
Module for configuring "telescope.nvim" plugin. More information is available at:
https://github.com/nvim-telescope/telescope.nvim
--]]

local M = {}

function M.config()
  local telescope = require("telescope")
  local actions = require("telescope.actions")

  -- Some default configuration values for Telescope.
  telescope.setup({
    defaults = {
      layout_strategy = "center", -- Customise the UI to be minimal (and although undesired the previewer gets disabled).
      multi_icon = " ", -- Disable the ugly & unnecessary icons beside the search results.
      prompt_prefix = "-> ", -- Configure the prompt with a "proper" Nerd Font icon for the pretty aesthetics.
      initial_mode = "normal", -- Configure Telescope to start the UI in Normal mode.
      file_ignore_patterns = { "^plugin/" }, -- Ignore the compiled file/folder generated by "packer.nvim".
      mappings = { -- Custom keymaps which are specific to Telescope. See ":h telescope.defaults.mappings" for more info.
        -- INFO: Following are the Normal mode keymappings.
        n = {
          ["q"] = actions.close, -- Press "q" (smallcase) to close Telescope.
        },
      },
    },
  })

  -- Load the many install Telescope extensions.
  telescope.load_extension("software-licenses")

  -- Load the native fuzzy-file finder as recommended in the official docs at:
  -- https://github.com/nvim-telescope/telescope.nvim/wiki/Extensions#sorter
  telescope.load_extension("fzf")
end

return M
