name: QA Checks

on:
  - push

jobs:
  runShellCheck:
    name: Lint Shell Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download and Setup Shellcheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download --repo koalaman/shellcheck --pattern "*.linux.x86_64.tar.xz"
          tar --extract --file "shellcheck*.tar.xz"
          cp shellcheck*/shellcheck /usr/local/bin/
          echo "Downloaded Shellcheck v{$(shellcheck --version)}"

      - name: Run Shellcheck
        run: shellcheck "setup"

  runStyLua:
    name: Format Lua Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run the Stylua formatter for Lua code
        uses: JohnnyMorganz/stylua-action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --check .

  runSeleneLinter:
    name: Lint Lua Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Selene to lint Lua code
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: dotfiles
          version: 0.16.0
