name: Automated Quality Control Checks

on: [push, pull_request]

jobs:
  runPrettier:
    # TODO: Implement the following GitHub Action instead of hacking stuff;
    # https://github.com/marketplace/actions/prettier-action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify Markdown, JSON & YAML Files
        uses: creyD/prettier_action@v4.0
        with:
          prettier_options: --write **/*.{json,md,yml}
          only_changed: true

  runShfmt:
    # TODO: Implement the following GitHub Action instead of hacking stuff;
    # https://github.com/marketplace/actions/sh-checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.4.0

      - name: Run the Shell Checker
        uses: luizm/action-sh-checker@master
        env:
          SHELLCHECK_OPTS: -e SC1004
          SHFMT_OPTS: -s -w
# TODO: Add a job for formatting Lua code as well which is used for
# configuring Neovim.

